version: '3.9'

services:
    db:
        image: postgres:13-alpine
        restart: unless-stopped
        volumes:
            - pg_data:/var/lib/postgresql/data/
        expose:
            - 5432
        environment:
            - POSTGRES_USER=user1
            - POSTGRES_PASSWORD=user1
            - POSTGRES_DB=netology_stocks_products

    migrate:
        build: .
        command: >
          sh -c "python /app/manage.py makemigrations --noinput &&
                 python /app/manage.py migrate --noinput"
        volumes:
            - ./Crud:/app
        depends_on:
            - db
        env_file:
            - .env

    django:
        restart: unless-stopped
        build: .
        command: sh -c "gunicorn --bind 0.0.0.0:8000 stocks_products.wsgi"
        volumes:
            - ./Crud:/app
            - static_data:/app/static
        depends_on:
            - migrate
        expose:
            - 8000
        environment:
            - DEBUG='false'
        env_file:
            - .env

    nginx:
        image: nginx:1.19.8-alpine
        restart: unless-stopped
        depends_on:
            - django
        ports:
            - "80:80"
        volumes:
            - static_data:/var/www/html/static
            - ./nginx-conf.conf:/etc/nginx/conf.d/default.conf

volumes:
    pg_data:
    static_data: